name: aind
channels:
- defaults
dependencies:
- mkl=2017.0.1=0
- numpy=1.11.3=py36_0
- pip=9.0.1=py36_1
- python=3.6.0=0
- scikit-learn=0.18.1=np111py36_1
- scipy=0.18.1=np111py36_1
- setuptools=27.2.0=py36_1
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py36_0
- pip:
  - hmmlearn==0.2.0
